name: Build Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy documentation
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen graphviz -y

      - name: Generate Doxygen documentation
        run: |
          cmake -S . -B build -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_DOCS=ON
          cmake --build build --target doc

      - name: Add .nojekyll file
        run: touch docs/html/.nojekyll

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
